package net.veloclient.launcher;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * The launcher's own version, read from {@code version.properties} - a
 * resource generated by {@code launcher/build.gradle}'s
 * {@code writeLauncherVersion} task from its single {@code launcherAppVersion}
 * variable, so this never drifts out of sync with what jpackage stamps onto
 * the installer. Falls back to a hardcoded value only for the rare case of
 * running from classes without that generated resource present (e.g. an IDE
 * run that skipped {@code processResources}).
 */
public final class AppVersion {

	public static final String VERSION = load();

	private AppVersion() {
	}

	private static String load() {
		try (InputStream in = AppVersion.class.getResourceAsStream("/net/veloclient/launcher/version.properties")) {
			if (in != null) {
				Properties props = new Properties();
				props.load(in);
				String version = props.getProperty("version");
				if (version != null && !version.isBlank()) {
					return version.trim();
				}
			}
		} catch (IOException ignored) {
			// Fall through to the hardcoded default below.
		}
		return "0.5.1";
	}
}
